version: "2"
volumes:
        web: {}

services:
        server:
                build:
                        context: ./compose
                        dockerfile: ./server/Dockerfile

                ports:
                        - "8066:80"
                depends_on:
                        - app
                volumes:
                        - web:/usr/share/nginx/html/dist
        
        app:
                build:
                        context: ./compose
                        dockerfile: ./app/Dockerfile
                volumes:
                        - web:/app/web
